=== nilsreiter/treeanno/data2-io/src/main/resources/Document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  targetNamespace="http://www.nilsreiter.de/xmlns/Document" xmlns="http://www.nilsreiter.de/xmlns/Document">

    
 
    <xsd:element name="root">
        <xsd:complexType>
        <xsd:sequence>
          <xsd:element name="document" type="documentType"></xsd:element>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="documentType">

      <xsd:sequence>

      	<xsd:element name="originaltext" type="xsd:string"
      		maxOccurs="1" minOccurs="1">
      	</xsd:element>

      	<xsd:element name="sentences" maxOccurs="1" minOccurs="1">

      		<xsd:complexType>
      			<xsd:sequence>
      				<xsd:element name="sentence" type="sentenceType"
      					maxOccurs="unbounded" minOccurs="0">
      				</xsd:element>
      			</xsd:sequence>
      		</xsd:complexType>
      	</xsd:element>
      	<xsd:element name="coreference" maxOccurs="1" minOccurs="1">
      		<xsd:complexType>
      			<xsd:sequence>
      				<xsd:element name="entity" type="entityType"
      					maxOccurs="unbounded" minOccurs="0">
      				</xsd:element>
      				<xsd:element name="singletons" maxOccurs="1"
      					minOccurs="0">
      					<xsd:complexType>
      						<xsd:sequence>
      							<xsd:element name="mention"
      								type="mentionType" maxOccurs="unbounded" minOccurs="0">
      							</xsd:element>
      						</xsd:sequence>
      					</xsd:complexType>
      				</xsd:element>
      			</xsd:sequence>
      		</xsd:complexType>
      	</xsd:element>
      	<xsd:element name="frames" maxOccurs="1" minOccurs="1">
      		<xsd:complexType>
      			<xsd:sequence>
      				<xsd:element name="frame" type="frameType"
      					maxOccurs="unbounded" minOccurs="0">
      				</xsd:element>
      				<xsd:element name="order" type="orderType"
      					maxOccurs="1" minOccurs="1">
      				</xsd:element>
      			</xsd:sequence>
      		</xsd:complexType>
      	</xsd:element>
      	<xsd:element name="chunks" maxOccurs="1" minOccurs="1">
      		<xsd:complexType>
      			<xsd:sequence>
      				<xsd:element name="chunk" type="chunkType"
      					maxOccurs="unbounded" minOccurs="0">
      				</xsd:element>
      			</xsd:sequence>
      		</xsd:complexType>
      	</xsd:element>
      	<xsd:element name="sections" maxOccurs="1" minOccurs="1">
      		<xsd:complexType>
      			<xsd:sequence>
      				<xsd:element name="section" type="sectionType"
      					maxOccurs="unbounded" minOccurs="0">
      				</xsd:element>
      			</xsd:sequence>
      		</xsd:complexType>
      	</xsd:element>
      	<xsd:element name="senses" maxOccurs="1" minOccurs="1">
      		<xsd:complexType>
      			<xsd:sequence>
      				<xsd:element name="sense" type="senseType"
      					maxOccurs="unbounded" minOccurs="0">
      				</xsd:element>
      			</xsd:sequence>
      		</xsd:complexType>
      	</xsd:element>
      	<xsd:element name="mantras" maxOccurs="1" minOccurs="0">
      		<xsd:complexType>
      			<xsd:sequence>
      				<xsd:element name="mantra" type="mantraType"
      					maxOccurs="unbounded" minOccurs="0">
      				</xsd:element>
      			</xsd:sequence>
      		</xsd:complexType>
      	</xsd:element>
      	<xsd:element name="events" maxOccurs="1" minOccurs="0">
      		<xsd:complexType>
      			<xsd:sequence>
      				<xsd:element name="event" type="eventType"
      					maxOccurs="unbounded" minOccurs="0">
      				</xsd:element>
      			</xsd:sequence>
      		</xsd:complexType>
      	</xsd:element>
      </xsd:sequence>
      <xsd:attribute ref="id"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="sentenceType">

      <xsd:sequence>

        <xsd:element name="token" type="tokenType" maxOccurs="unbounded" minOccurs="1">
        </xsd:element>
      </xsd:sequence>

      <xsd:attribute ref="id"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tokenType">


      <xsd:sequence>
        <xsd:element name="frame" type="frameRefType"
          maxOccurs="unbounded" minOccurs="0">
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="word" type="xsd:string"></xsd:attribute>

      <xsd:attribute name="lemma" type="xsd:string" use="required"></xsd:attribute>

      <xsd:attribute name="sense" type="xsd:IDREF"></xsd:attribute>

      <xsd:attribute name="characterOffsetBegin" type="xsd:int"></xsd:attribute>

      <xsd:attribute name="characterOffsetEnd" type="xsd:int"
        use="required">
      </xsd:attribute>

      <xsd:attribute name="governor" type="xsd:IDREF"></xsd:attribute>

      <xsd:attribute name="deprel" type="xsd:string"></xsd:attribute>
      <xsd:attribute ref="id"></xsd:attribute>
      <xsd:attribute name="pos" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute ref="OldId"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="frameType">

      <xsd:sequence>


            <xsd:element ref="token"></xsd:element>
            <xsd:element name="frame_element" maxOccurs="unbounded"
      		minOccurs="0">

      		<xsd:complexType>
      			<xsd:sequence maxOccurs="unbounded" minOccurs="1">
      				<xsd:choice maxOccurs="unbounded" minOccurs="1">
      					<xsd:element name="mention"
      						type="mentionRefType" maxOccurs="unbounded" minOccurs="0">
      					</xsd:element>
      					<xsd:element name="token" type="tokenRefType"
      						maxOccurs="unbounded" minOccurs="0">
      					</xsd:element>
      					<xsd:element name="head" type="tokenRefType"
      						maxOccurs="1" minOccurs="0">
      					</xsd:element>
      				</xsd:choice>
      			</xsd:sequence>
      			<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
      			<xsd:attribute ref="id"></xsd:attribute>
      		</xsd:complexType>
      	</xsd:element>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"></xsd:attribute>
      <xsd:attribute ref="id"></xsd:attribute>
      <xsd:attribute ref="OldId"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="tokenRefType">

      <xsd:attribute name="idref" type="xsd:IDREF"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="chunkType">

      <xsd:sequence>

        <xsd:element name="token" type="tokenRefType"
          maxOccurs="unbounded" minOccurs="1">
        </xsd:element>
      </xsd:sequence>


      <xsd:attribute name="category" type="xsd:string"></xsd:attribute>
      <xsd:attribute ref="id"></xsd:attribute>
      <xsd:attribute name="sentence" type="xsd:IDREF"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="senseType">


      <xsd:attribute name="wordnet" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute ref="id"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="sectionType">

      <xsd:sequence>
        <xsd:element name="sentence" type="sentenceRefType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      </xsd:sequence>
      <xsd:attribute ref="id"></xsd:attribute>
    </xsd:complexType>



    <xsd:attribute name="id" type="xsd:ID"></xsd:attribute>

    <xsd:complexType name="entityType">

      <xsd:sequence>

        <xsd:element name="sense" type="senseRefType" maxOccurs="1" minOccurs="0">
        </xsd:element>

        <xsd:element name="mention" type="mentionType" maxOccurs="unbounded" minOccurs="1">
        </xsd:element>
      </xsd:sequence>

      <xsd:attribute ref="id"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="senseRefType">

      <xsd:attribute name="idref" type="xsd:IDREF"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="mentionType">

      <xsd:sequence>

        <xsd:element name="token" type="tokenRefType" maxOccurs="unbounded" minOccurs="1">
        </xsd:element>

        <xsd:element name="fe" type="frameElementRefType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      </xsd:sequence>

      <xsd:attribute ref="id"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="frameElementRefType">
      
        <xsd:attribute name="idref" type="xsd:IDREF"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="mentionRefType">
      <xsd:attribute name="idref" type="xsd:IDREF"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="refType">
      <xsd:attribute name="idref" type="xsd:IDREF"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="frameRefType">
      <xsd:attribute name="idref" type="xsd:IDREF"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="orderType">
      <xsd:sequence>
        <xsd:element name="frame" type="frameRefType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
      </xsd:sequence>
      <xsd:attribute name="type">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="temporal"></xsd:enumeration>
            <xsd:enumeration value="textual"></xsd:enumeration>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="sentenceRefType">
      <xsd:attribute name="idref" type="xsd:IDREF"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="mantraType">
      <xsd:sequence>
        <xsd:element name="token" type="tokenRefType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    </xsd:complexType>

    <xsd:attribute name="OldId" type="xsd:string"></xsd:attribute>


    <xsd:complexType name="eventType">
    	<xsd:sequence>
            <xsd:element ref="anchor"></xsd:element>
            <xsd:element name="argument" type="argumentType"
    			maxOccurs="unbounded" minOccurs="0">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute ref="id"></xsd:attribute>
    	<xsd:attribute name="class" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="argumentType">
    	<xsd:sequence>
    		<xsd:element ref="target" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="role" type="xsd:string"></xsd:attribute>
    </xsd:complexType>



    <xsd:element name="target" type="tokenRefType"></xsd:element>

    <xsd:element name="anchor" type="refType"></xsd:element>
    <xsd:element name="token" type="tokenRefType"></xsd:element>

</xsd:schema>

=== nilsreiter/treeanno/data2-io/src/test/resources/r0010.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.nilsreiter.de/xmlns/Document Document.xsd"
	xmlns="http://www.nilsreiter.de/xmlns/Document">
  <document id="r0010">
    <originaltext><![CDATA[Now the rules for the night vigil for the goddess Ṣaṣṭhī in the sixth night after delivery. 
Let the child take a bath.
Wherever Viṣṇu is established i.e. the place where the ritual is commenced, exactly there the visarjana should be performed. 
Send a share of the bali to the pikhālakhu. 
Make a ritual bath of the statue of Nārāyaṇa. 
Welcome the child with a white cloth at the auspicious time. 
Give a finger to the boy to welcome him. 
Place a person on the door holding a sword. 
Here hand over the flower basket. Worship Viṣṇu according to the custom i.e. with incense, light, recitations and prayers. 
Worship the Brahmin. 
Recite the svasti no mimītā ; the kanikrada; the āśuḥ śiśāno; the yaj jāgrato; themantra; the agnes tanūr and the vayam̐ soma.
Worship at the birth place of the child in the temple of Ṣaṣṭhī at the auspicious time. 
Place a grinding stone. 
Offer a lamp with six wicks to the Ṣaṣṭhī goddess. 
Offer fragrant materials etc. 
Recitation and the following prayer: "Śivā, Sambhūti, Prīti, Saṃtati, Anusūyā and Kṣemā – these six are the names of the Ṣaṣṭhī goddess." 
Offer fragrant materials etc. 
Give flower during the recitation of the śāntikamantra. 
Make the ritual decision for food. 
dakṣiṇā should be given to the gods and priest. 
Auspicious recitations. 
Blessings from the gods in the form of prasāda. 
Release the deities. 
Send a share of the bali to the pikhālākhu. 
Ritual washing. 
Fragrant materials etc. 
Blessings. 
Speak a few pleasing words to the newborn child. 
Here end the rules for the night vigil for the goddess Ṣaṣṭhī. 
Hail.
]]></originaltext>
    <sentences>
      <sentence id="s0">
        <token id="t224" word="Now" lemma="now" deprel="ADVMOD" sense="sen62" characterOffsetBegin="0" characterOffsetEnd="3" governor="t278" pos="RB" OldId="r0010_0_t_0"/>
        <token id="t255" word="the" lemma="the" deprel="DET" characterOffsetBegin="4" characterOffsetEnd="7" governor="t278" pos="DT" OldId="r0010_0_t_1"/>
        <token id="t278" word="rules" lemma="rule" sense="sen26" characterOffsetBegin="8" characterOffsetEnd="13" pos="NNS" OldId="r0010_0_t_2">
          <frame idref="f0"/>
        </token>
        <token id="t263" word="for" lemma="for" deprel="PREP" characterOffsetBegin="14" characterOffsetEnd="17" governor="t278" pos="IN" OldId="r0010_0_t_3"/>
        <token id="t292" word="the" lemma="the" deprel="DET" characterOffsetBegin="18" characterOffsetEnd="21" governor="t41" pos="DT" OldId="r0010_0_t_4"/>
        <token id="t23" word="night" lemma="night" deprel="NN" sense="sen5" characterOffsetBegin="22" characterOffsetEnd="27" governor="t41" pos="NN" OldId="r0010_0_t_5">
          <frame idref="f1"/>
        </token>
        <token id="t41" word="vigil" lemma="vigil" deprel="POBJ" sense="sen11" characterOffsetBegin="28" characterOffsetEnd="33" governor="t263" pos="NN" OldId="r0010_0_t_6"/>
        <token id="t12" word="for" lemma="for" deprel="PREP" characterOffsetBegin="34" characterOffsetEnd="37" governor="t41" pos="IN" OldId="r0010_0_t_7"/>
        <token id="t75" word="the" lemma="the" deprel="DET" characterOffsetBegin="38" characterOffsetEnd="41" governor="t53" pos="DT" OldId="r0010_0_t_8"/>
        <token id="t80" word="goddess" lemma="goddess" deprel="NN" sense="sen12" characterOffsetBegin="42" characterOffsetEnd="49" governor="t53" pos="NN" OldId="r0010_0_t_9"/>
        <token id="t53" word="Ṣaṣṭhī" lemma="ṣaṣṭhī" deprel="POBJ" characterOffsetBegin="50" characterOffsetEnd="56" governor="t12" pos="NN" OldId="r0010_0_t_10"/>
        <token id="t102" word="in" lemma="in" deprel="PREP" characterOffsetBegin="57" characterOffsetEnd="59" governor="t53" pos="IN" OldId="r0010_0_t_11"/>
        <token id="t89" word="the" lemma="the" deprel="DET" characterOffsetBegin="60" characterOffsetEnd="63" governor="t133" pos="DT" OldId="r0010_0_t_12"/>
        <token id="t95" word="sixth" lemma="sixth" deprel="AMOD" sense="sen25" characterOffsetBegin="64" characterOffsetEnd="69" governor="t133" pos="JJ" OldId="r0010_0_t_13"/>
        <token id="t133" word="night" lemma="night" deprel="POBJ" sense="sen5" characterOffsetBegin="70" characterOffsetEnd="75" governor="t102" pos="NN" OldId="r0010_0_t_14">
          <frame idref="f2"/>
        </token>
        <token id="t121" word="after" lemma="after" deprel="PREP" characterOffsetBegin="76" characterOffsetEnd="81" governor="t133" pos="IN" OldId="r0010_0_t_15"/>
        <token id="t124" word="delivery" lemma="delivery" deprel="POBJ" sense="sen36" characterOffsetBegin="82" characterOffsetEnd="90" governor="t121" pos="NN" OldId="r0010_0_t_16"/>
        <token id="t178" word="." lemma="." deprel="PUNCT" characterOffsetBegin="90" characterOffsetEnd="91" governor="t278" pos="." OldId="r0010_0_t_17"/>
      </sentence>
      <sentence id="s1">
        <token id="t163" word="Let" lemma="let" sense="sen45" characterOffsetBegin="93" characterOffsetEnd="96" pos="VB" OldId="r0010_1_t_0">
          <frame idref="f3"/>
        </token>
        <token id="t158" word="the" lemma="the" deprel="DET" characterOffsetBegin="97" characterOffsetEnd="100" governor="t218" pos="DT" OldId="r0010_1_t_1"/>
        <token id="t218" word="child" lemma="child" deprel="NSUBJ" sense="sen4" characterOffsetBegin="101" characterOffsetEnd="106" governor="t198" pos="NN" OldId="r0010_1_t_2"/>
        <token id="t198" word="take" lemma="take" deprel="CCOMP" sense="sen53" characterOffsetBegin="107" characterOffsetEnd="111" governor="t163" pos="VB" OldId="r0010_1_t_3">
          <frame idref="f4"/>
        </token>
        <token id="t195" word="a" lemma="a" deprel="DET" characterOffsetBegin="112" characterOffsetEnd="113" governor="t250" pos="DT" OldId="r0010_1_t_4"/>
        <token id="t250" word="bath" lemma="bath" deprel="DOBJ" sense="sen70" characterOffsetBegin="114" characterOffsetEnd="118" governor="t198" pos="NN" OldId="r0010_1_t_5"/>
        <token id="t233" word="." lemma="." deprel="PUNCT" characterOffsetBegin="118" characterOffsetEnd="119" governor="t163" pos="." OldId="r0010_1_t_6"/>
      </sentence>
      <sentence id="s2">
        <token id="t222" word="Wherever" lemma="wherever" deprel="PREP" characterOffsetBegin="120" characterOffsetEnd="128" governor="t262" pos="IN" OldId="r0010_2_t_0"/>
        <token id="t288" word="Viṣṇu" lemma="Viṣṇu" deprel="POBJ" characterOffsetBegin="129" characterOffsetEnd="134" governor="t222" pos="NNP" OldId="r0010_2_t_1"/>
        <token id="t279" word="is" lemma="be" deprel="AUXPASS" sense="sen13" characterOffsetBegin="135" characterOffsetEnd="137" governor="t262" pos="VBZ" OldId="r0010_2_t_2"/>
        <token id="t262" word="established" lemma="establish" deprel="ADVCL" sense="sen72" characterOffsetBegin="138" characterOffsetEnd="149" governor="t175" pos="VBN" OldId="r0010_2_t_3"/>
        <token id="t65" word="i.e." lemma="i.e." deprel="DOBJ" characterOffsetBegin="150" characterOffsetEnd="154" governor="t262" pos="FW" OldId="r0010_2_t_4"/>
        <token id="t70" word="the" lemma="the" deprel="DEP" characterOffsetBegin="155" characterOffsetEnd="158" governor="t5" pos="DT" OldId="r0010_2_t_5"/>
        <token id="t5" word="place" lemma="place" deprel="DEP" characterOffsetBegin="159" characterOffsetEnd="164" governor="t65" pos="VBP" OldId="r0010_2_t_6">
          <frame idref="f5"/>
        </token>
        <token id="t13" word="where" lemma="where" deprel="ADVMOD" characterOffsetBegin="165" characterOffsetEnd="170" governor="t142" pos="WRB" OldId="r0010_2_t_7"/>
        <token id="t25" word="the" lemma="the" deprel="DET" characterOffsetBegin="171" characterOffsetEnd="174" governor="t115" pos="DT" OldId="r0010_2_t_8"/>
        <token id="t115" word="ritual" lemma="ritual" deprel="NSUBJPASS" characterOffsetBegin="175" characterOffsetEnd="181" governor="t142" pos="NN" OldId="r0010_2_t_9">
          <frame idref="f6"/>
        </token>
        <token id="t128" word="is" lemma="be" deprel="AUXPASS" characterOffsetBegin="182" characterOffsetEnd="184" governor="t142" pos="VBZ" OldId="r0010_2_t_10"/>
        <token id="t142" word="commenced" lemma="commence" deprel="ADVCL" characterOffsetBegin="185" characterOffsetEnd="194" governor="t5" pos="VBN" OldId="r0010_2_t_11"/>
        <token id="t81" word="," lemma="," deprel="PUNCT" sense="sen22" characterOffsetBegin="194" characterOffsetEnd="195" governor="t5" pos="," OldId="r0010_2_t_12"/>
        <token id="t97" word="exactly" lemma="exactly" deprel="ADVMOD" sense="sen13" characterOffsetBegin="196" characterOffsetEnd="203" governor="t104" pos="RB" OldId="r0010_2_t_13">
          <frame idref="f7"/>
        </token>
        <token id="t104" word="there" lemma="there" deprel="ADVMOD" sense="sen27" characterOffsetBegin="204" characterOffsetEnd="209" governor="t262" pos="RB" OldId="r0010_2_t_14">
          <frame idref="f8"/>
        </token>
        <token id="t202" word="the" lemma="the" deprel="DET" characterOffsetBegin="210" characterOffsetEnd="213" governor="t3" pos="DT" OldId="r0010_2_t_15"/>
        <token id="t3" word="visarjana" lemma="visarjana" deprel="NSUBJPASS" characterOffsetBegin="214" characterOffsetEnd="223" governor="t175" pos="FW" OldId="r0010_2_t_17">
          <frame idref="f9"/>
        </token>
        <token id="t164" word="should" lemma="should" deprel="AUX" characterOffsetBegin="224" characterOffsetEnd="230" governor="t175" pos="MD" OldId="r0010_2_t_18"/>
        <token id="t154" word="be" lemma="be" deprel="AUXPASS" sense="sen22" characterOffsetBegin="231" characterOffsetEnd="233" governor="t175" pos="VB" OldId="r0010_2_t_19"/>
        <token id="t175" word="performed" lemma="perform" characterOffsetBegin="234" characterOffsetEnd="243" pos="VBN" OldId="r0010_2_t_20">
          <frame idref="f10"/>
