=== nilsreiter/treeanno/de.saar.coli.salsa.reiter.framenet/src/test/resources/corpusV1_1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This is the DTD for the XXXCorpus.xml files, which contain information
about the annotation objects of a document: document, paragraph, sentence, annotationSets,
layers, etc.  Its format can be summarized as:

<corpus>
 <documents>
  <document>*
   <paragraphs>
    <paragraph>*
     <sentences>
      <sentence>*
       <text>
       <annotationSets>
        <annotationSet>
          <layers>
           <layer>*
             <labels>
               <label>*
-->




<!ELEMENT corpus (documents)> 
<!ATTLIST corpus ID NMTOKEN #REQUIRED
            name CDATA #REQUIRED>

<!ELEMENT documents (document*)>

<!ELEMENT document (paragraphs)>
<!ATTLIST document ID NMTOKEN #REQUIRED
                   description CDATA #REQUIRED>

<!ELEMENT paragraphs (paragraph*)>
<!ELEMENT paragraph (sentences)>
<!ATTLIST paragraph ID NMTOKEN #REQUIRED
                   documentOrder NMTOKEN #REQUIRED>
<!ELEMENT sentences (sentence*)>
<!ELEMENT sentence (text, annotationSets)>
<!ATTLIST sentence ID NMTOKEN #REQUIRED>
<!ELEMENT text (#PCDATA)>
<!ELEMENT annotationSets (annotationSet*)>
<!ELEMENT annotationSet (layers?)>
<!ATTLIST annotationSet ID NMTOKEN #REQUIRED
						status CDATA #REQUIRED
                        frameName CDATA #IMPLIED
                        frameRef NMTOKEN #IMPLIED
                        lexUnitRef NMTOKEN #IMPLIED 
                        luName CDATA #IMPLIED>

<!ELEMENT layers (layer*)>
<!ELEMENT layer (labels?)>
<!ATTLIST layer ID NMTOKEN #REQUIRED
            name CDATA #REQUIRED
			rank NMTOKEN #IMPLIED
>
<!ELEMENT labels (label*)>
<!ELEMENT label EMPTY>
<!ATTLIST label ID NMTOKEN #REQUIRED
            name CDATA #REQUIRED
	    start NMTOKEN #IMPLIED
	    end NMTOKEN #IMPLIED
      itype CDATA #IMPLIED>

=== nilsreiter/treeanno/de.saar.coli.salsa.reiter.framenet/src/test/resources/FNCorpus-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE corpus SYSTEM "corpusV1_1.dtd">

<corpus ID="134" name="NTI">
  <documents>
    <document ID="458" description="LibyaCountry1">
      <paragraphs>
        <paragraph ID="9538" documentOrder="1">
          <sentences>
            <sentence ID="1271623">
              <text>Introduction</text>
              <annotationSets>
                <annotationSet ID="1989305" status="UNANN">
                  <layers>
                    <layer ID="10161481" name="NER" />
                  </layers>
                </annotationSet>
              </annotationSets>
            </sentence>
          </sentences>
        </paragraph>
        <paragraph ID="9539" documentOrder="2">
          <sentences>
            <sentence ID="1271624">
              <text>Libya has shown interest in and taken steps to acquire weapons of mass destruction ( WMD ) and their delivery systems .</text>
              <annotationSets>
                <annotationSet ID="1989306" status="UNANN">
                  <layers>
                    <layer ID="10161483" name="NER">
                      <labels>
                        <label name="GPE" ID="31741981" start="0" end="4" />
                        <label name="WEA" ID="31741988" start="55" end="81" />
                        <label name="WEA" ID="31741989" start="85" end="87" />
                      </labels>
                    </layer>
                  </layers>
                </annotationSet>
                <annotationSet ID="1989350" status="MANUAL" frameName="Emotion_directed" frameRef="46" luName="interest.n" lexUnitRef="8988">
                  <layers>
                    <layer ID="10161590" name="Target">
                      <labels>
                        <label name="Target" ID="31697824" start="16" end="23" />
                      </labels>
                    </layer>
                    <layer ID="10161591" name="FE" rank="1">
                      <labels>
                        <label name="Experiencer" ID="31697842" start="0" end="4" />
                        <label name="Stimulus" ID="31697854" start="25" end="26" />
                        <label name="Stimulus" ID="31697858" start="55" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10161592" name="GF">
                      <labels>
                        <label name="Ext" ID="31697844" start="0" end="4" />
                        <label name="Dep" ID="31697856" start="25" end="26" />
                        <label name="Dep" ID="31697860" start="55" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10161593" name="PT">
                      <labels>
                        <label name="NP" ID="31697843" start="0" end="4" />
                        <label name="PP" ID="31697855" start="25" end="26" />
                        <label name="PP" ID="31697859" start="55" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10161594" name="Other" />
                    <layer ID="10161595" name="Sent" />
                    <layer ID="10161596" name="Noun">
                      <labels>
                        <label name="Supp" ID="31697832" start="10" end="14" />
                      </labels>
                    </layer>
                  </layers>
                </annotationSet>
                <annotationSet ID="1989358" status="MANUAL" frameName="Getting" frameRef="179" luName="acquire.v" lexUnitRef="7500">
                  <layers>
                    <layer ID="10161646" name="Target">
                      <labels>
                        <label name="Target" ID="31697862" start="47" end="53" />
                      </labels>
                    </layer>
                    <layer ID="10161647" name="FE" rank="1">
                      <labels>
                        <label name="Recipient" ID="31697888" start="0" end="4" />
                        <label name="Theme" ID="31697898" start="55" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10161648" name="GF">
                      <labels>
                        <label name="Ext" ID="31697890" start="0" end="4" />
                        <label name="Obj" ID="31697903" start="55" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10161649" name="PT">
                      <labels>
                        <label name="NP" ID="31697894" start="0" end="4" />
                        <label name="NP" ID="31697904" start="55" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10161650" name="Other" />
                    <layer ID="10161651" name="Sent" />
                    <layer ID="10161652" name="Verb" />
                  </layers>
                </annotationSet>
                <annotationSet ID="1989377" status="MANUAL" frameName="Intentionally_act" frameRef="198" luName="step.n" lexUnitRef="10613">
                  <layers>
                    <layer ID="10161780" name="Target">
                      <labels>
                        <label name="Target" ID="31698022" start="38" end="42" />
                      </labels>
                    </layer>
                    <layer ID="10161781" name="FE" rank="1">
                      <labels>
                        <label name="Agent" ID="31698031" start="0" end="4" />
                        <label name="Purpose" ID="31698040" start="44" end="116" />
                        <label name="Act" ID="31698053" start="38" end="42" />
                      </labels>
                    </layer>
                    <layer ID="10161782" name="GF">
                      <labels>
                        <label name="Ext" ID="31698032" start="0" end="4" />
                        <label name="Dep" ID="31698066" start="44" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10161783" name="PT">
                      <labels>
                        <label name="NP" ID="31698034" start="0" end="4" />
                        <label name="VPto" ID="31698067" start="44" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10161784" name="Other" />
                    <layer ID="10161785" name="Sent" />
                    <layer ID="10161786" name="Noun">
                      <labels>
                        <label name="Supp" ID="31698027" start="32" end="36" />
                      </labels>
                    </layer>
                  </layers>
                </annotationSet>
                <annotationSet ID="1989626" status="MANUAL" frameName="Weapon" frameRef="426" luName="weapon of mass destruction.n" lexUnitRef="10707">
                  <layers>
                    <layer ID="10163401" name="Target">
                      <labels>
                        <label name="Target" ID="31699594" start="55" end="81" />
                      </labels>
                    </layer>
                    <layer ID="10163402" name="FE" rank="1">
                      <labels>
                        <label name="Weapon" ID="31699595" start="55" end="81" />
                      </labels>
                    </layer>
                    <layer ID="10163403" name="GF" />
                    <layer ID="10163404" name="PT" />
                    <layer ID="10163405" name="Other" />
                    <layer ID="10163406" name="Sent" />
                    <layer ID="10163407" name="Noun" />
                    <layer ID="10163408" name="FE" rank="2">
                      <labels>
                        <label name="Use" ID="31699596" start="63" end="81" />
                      </labels>
                    </layer>
                  </layers>
                </annotationSet>
                <annotationSet ID="2004747" status="MANUAL" frameName="Gizmo" frameRef="106" luName="system.n" lexUnitRef="11690">
                  <layers>
                    <layer ID="10256085" name="Target">
                      <labels>
                        <label name="Target" ID="31907114" start="110" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10256086" name="FE" rank="1">
                      <labels>
                        <label name="Use" ID="31907115" start="101" end="108" />
                        <label name="Gizmo" ID="31907118" start="110" end="116" />
                      </labels>
                    </layer>
                    <layer ID="10256087" name="GF">
                      <labels>
                        <label name="Dep" ID="31907117" start="101" end="108" />
                      </labels>
                    </layer>
                    <layer ID="10256088" name="PT">
                      <labels>
                        <label name="N" ID="31907116" start="101" end="108" />
                      </labels>
                    </layer>
                    <layer ID="10256089" name="Other" />
                    <layer ID="10256090" name="Sent" />
                    <layer ID="10256091" name="Noun" />
                  </layers>
                </annotationSet>
              </annotationSets>
            </sentence>
            <sentence ID="1271625">
              <text>Indeed , it is one of the few states to have employed chemical weapons in a conflict ( Chad , 1987 ) .</text>
              <annotationSets>
                <annotationSet ID="1989307" status="UNANN">
                  <layers>
                    <layer ID="10161485" name="NER">
                      <labels>
                        <label name="location" ID="31741982" start="87" end="90" />
                        <label name="date" ID="31741983" start="94" end="97" />
